name: "creating the workflow for printing hellow world, date on push"

on:
    push:
        # branches:
        #     - master
        #     - production

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "Printing hello world"
              run: echo "Hello world"
            - name: "Printing todays date"
              run: date
    
    current_directory:
        runs-on: ubuntu-latest
        steps:
            - name: "printing current directory"
              run: pwd

